In [1]:
import numpy as np

![Image](https://s-i.huffpost.com/gen/1843881/images/o-DECISION-facebook.jpg)

In [2]:
A = np.array([
    [1., 1., 0.25],
    [1., 1., 0.2],
    [4., 5., 1.]
])
AR = np.array([
    [1., 2.],
    [0.5, 1.]
])
AM = np.array([
    [1., 0.5],
    [2., 1.]
])
AA = np.array([
    [1., 1.],
    [1., 1.]
])

In [3]:
def norm(X):
    return np.sum(X, axis=1) / np.sum(X)

Let's find a wegith vector for our criterias.

In [4]:
W = norm(A)
W

array([ 0.15570934,  0.15224913,  0.69204152])

Now we can build a norms for our criterias.

In [5]:
X = np.vstack((norm(AR), norm(AM), norm(AA)))
X

array([[ 0.66666667,  0.33333333],
       [ 0.33333333,  0.66666667],
       [ 0.5       ,  0.5       ]])

And scale them properly.

In [6]:
usefulness = np.dot(X.T, W)
usefulness

array([ 0.5005767,  0.4994233])

So that we choose the first one.